[tool.pyright]
typeCheckingMode = "basic"
pythonVersion = "3.9, 3.10, 3.11"
ignore = ["examples/**"]

reportMissingImports = false
reportMissingTypeStubs = false
reportMissingModuleSource = false


[tool.pylint]
good-names="os, id, op, r, g, b"

[tool.pylint.messages_control]
max-attributes = 15
max-args = 10
max-public-methods = 50
max-locals = 30
max-line-length=120
disable = """
logging-fstring-interpolation,
missing-module-docstring,
missing-class-docstring,
too-few-public-methods,
protected-access,
missing-function-docstring,
no-name-in-module
"""